### ISSUE TITLE
CUDA error: no CUDA-capable device is detected when prepare data promptasr

### ISSUE THREAD

**Issue by quanganhdao2k2** [k2-fsa/icefall#1457]
Hello everyone,

I am currently reproducing the results of PromptASR. However, I am encountering an issue when running prepare.sh stage 7. I have checked the GPU and the environment, but it still doesn't work. It continues to use the CPU and takes a considerable amount of time to process.
I have checked the code [here](https://github.com/k2-fsa/icefall/blob/e2fcb42f5f176d9e39eb38506ab99d0a3adaf202/egs/libriheavy/ASR/local/compute_fbank_libriheavy.py#L186)

![Screenshot from 2024-01-12 12-00-02](https://github.com/k2-fsa/icefall/assets/144792281/3259427a-9493-4265-9bf5-f0a931891dfa)
![Screenshot from 2024-01-12 11-58-58](https://github.com/k2-fsa/icefall/assets/144792281/56697033-3c98-48d6-ad86-83aaa4b593c6)
Here is the error image I encountered. Has anyone experienced a similar issue? Thank you for any contributions from you.

**Comment by csukuangfj** [comment]
That is strange.

Could you give more logs?

**Comment by quanganhdao2k2** [comment]
Thank you for your feedback. I must have made a mistake somewhere. Here is the environment I have installed:

```python
!pip install torch==2.1.2+cu121 -f https://download.pytorch.org/whl/torch_stable.html
!pip install k2==1.24.4.dev20231221+cuda12.1.torch2.1.2 -f https://k2-fsa.github.io/k2/cuda.html
!pip install git+https://github.com/lhotse-speech/lhotse
!pip install kaldifeat==1.25.3.dev20231221+cuda12.1.torch2.1.2 -f https://csukuangfj.github.io/kaldifeat/cuda.html
```

For testing purposes, I ran `prepare.sh` with LibriHeavy small. I modified the code to change "medium large" to small in the [link](https://github.com/k2-fsa/icefall/blob/master/egs/libriheavy/ASR/prepare.sh#L168-L183) and only ran stages 0 ,1, 3, 6, 7. I encountered an error at stage 7. Then I fix "cpu" to "gpu". The output looks like this:
```python
2024-01-08 12:05:47 (prepare.sh:56:main) dl_dir: [/media/slp/slp_4T/Thachhs/ai_test/icefall/egs/libriheavy/ASR/download](https://file+.vscode-resource.vscode-cdn.net/media/slp/slp_4T/Thachhs/ai_test/icefall/egs/libriheavy/ASR/download)
2024-01-08 12:05:47 (prepare.sh:180:main) Stage 7: Compute fbank for small subsets
2024-01-08 12:05:48,833 INFO [compute_fbank_libriheavy.py:236] {'manifest_dir': 'data/manifests', 'fbank_dir': 'data/fbank', 'subset': 'small', 'num_workers': 15, 'batch_duration': 600.0, 'perturb_speed': False, 'use_splits': True, 'num_splits': 16, 'start': 60, 'stop': 80}
Traceback (most recent call last):
  File "/media/slp/slp_4T/Thachhs/ai_test/icefall/egs/libriheavy/ASR/./local/compute_fbank_libriheavy.py", line 240, in <module>
    compute_fbank_libriheavy_splits(args)
  File "/media/slp/slp_4T/Thachhs/ai_test/icefall/egs/libriheavy/ASR/./local/compute_fbank_libriheavy.py", line 187, in compute_fbank_libriheavy_splits
    extractor = KaldifeatFbank(KaldifeatFbankConfig(device="cuda"))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/slp/slp_4T/Thachhs/lhotse/lhotse/features/kaldifeat.py", line 190, in __init__
    self.extractor = kaldifeat.Fbank(
                     ^^^^^^^^^^^^^^^^
  File "/home/slp/anaconda3/envs/icefall_test/lib/python3.11/site-packages/kaldifeat/fbank.py", line 13, in __init__
    self.computer = _kaldifeat.Fbank(opts)
                    ^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: no CUDA-capable device is detected
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Device-side assertions were explicitly omitted for this error check; the error probably arose while initializing the DSA handlers.
Exception raised from c10_cuda_check_implementation at ../c10/cuda/CUDAException.cpp:44 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f21c5f00617 in [/home/slp/anaconda3/envs/icefall_test/lib/python3.11/site-packages/torch/lib/libc10.so](https://file+.vscode-resource.vscode-cdn.net/home/slp/anaconda3/envs/icefall_test/lib/python3.11/site-packages/torch/lib/libc10.so))
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7f21c5ebb98d in [/home/slp/anaconda3/envs/icefall_test/lib/python3.11/site-packages/torch/lib/libc10.so](https://file+.vscode-resource.vscode-cdn.net/home/slp/anaconda3/envs/icefall_test/lib/python3.11/site-packages/torch/lib/libc10.so))
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x118 (0x7f219d535838 in [/home/slp/anaconda3/envs/icefall_test/lib/python3.11/site-packages/torch/lib/libc10_cuda.so](https://file+.vscode-resource.vscode-cdn.net/home/slp/anaconda3/envs/icefall_test/lib/python3.11/site-packages/torch/lib/libc10_cuda.so))
frame #3: c10::cuda::CUDAKernelLaunchRegistry::CUDAKernelLaunchRegistry() + 0x9d (0x7f219d534f0d in [/home/slp/anaconda3/envs/icefall_test/lib/python3.11/site-packages/torch/lib/libc10_cuda.so](https://file+.vscode-resource.vscode-cdn.net/home/slp/anaconda3/envs/icefall_test/lib/python3.11/site-packages/torch/lib/libc10_cuda.so))
frame #4: c10::cuda::CUDAKernelLaunchRegistry::get_singleton_ref() + 0x44 (0x7f219d5350d4 in [/home/slp/anaconda3/envs/icefall_test/lib/python3.11/site-packages/torch/lib/libc10_cuda.so](https://file+.vscode-resource.vscode-cdn.net/home/slp/anaconda3/envs/icefall_test/lib/python3.11/site-packages/torch/lib/libc10_cuda.so))
frame #5: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x35 (0x7f219d535755 in [/home/slp/anaconda3/envs/icefall_test/lib/python3.11/site-packages/torch/lib/libc10_cuda.so](https://file+.vscode-resource.vscode-cdn.net/home/slp/anaconda3/envs/icefall_test/lib/python3.11/site-packages/torch/lib/libc10_cuda.so))
frame #6: <unknown function> + 0x247ee (0x7f219d5037ee in [/home/slp/anaconda3/envs/icefall_test/lib/python3.11/site-packages/torch/lib/libc10_cuda.so](https://file+.vscode-resource.vscode-cdn.net/home/slp/anaconda3/envs/icefall_test/lib/python3.11/site-packages/torch/lib/libc10_cuda.so))
frame #7: at::native::to(at::Tensor const&, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>, bool, bool, c10::optional<c10::MemoryFormat>) + 0x179 (0x7f2183e895e9 in [/home/slp/anaconda3/envs/icefall_test/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so](https://file+.vscode-resource.vscode-cdn.net/home/slp/anaconda3/envs/icefall_test/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so))
frame #8: <unknown function> + 0x2e06b71 (0x7f2184e06b71 in [/home/slp/anaconda3/envs/icefall_test/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so](https://file+.vscode-resource.vscode-cdn.net/home/slp/anaconda3/envs/icefall_test/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so))
frame #9: at::_ops::to_dtype_layout::call(at::Tensor const&, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>, bool, bool, c10::optional<c10::MemoryFormat>) + 0x203 (0x7f21845b42b3 in [/home/slp/anaconda3/envs/icefall_test/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so](https://file+.vscode-resource.vscode-cdn.net/home/slp/anaconda3/envs/icefall_test/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so))
frame #10: <unknown function> + 0x20e27 (0x7f211b041e27 in [/home/slp/anaconda3/envs/icefall_test/lib/python3.11/site-packages/kaldifeat/lib64/libkaldifeat_core.so](https://file+.vscode-resource.vscode-cdn.net/home/slp/anaconda3/envs/icefall_test/lib/python3.11/site-packages/kaldifeat/lib64/libkaldifeat_core.so))
frame #11: kaldifeat::MelBanks::MelBanks(kaldifeat::MelBanksOptions const&, kaldifeat::FrameExtractionOptions const&, float, c10::Device) + 0xb01 (0x7f211b043121 in [/home/slp/anaconda3/envs/icefall_test/lib/python3.11/site-packages/kaldifeat/lib64/libkaldifeat_core.so](https://file+.vscode-resource.vscode-cdn.net/home/slp/anaconda3/envs/icefall_test/lib/python3.11/site-packages/kaldifeat/lib64/libkaldifeat_core.so))
frame #12: kaldifeat::FbankComputer::GetMelBanks(float) + 0x90 (0x7f211b02e540 in [/home/slp/anaconda3/envs/icefall_test/lib/python3.11/site-packages/kaldifeat/lib64/libkaldifeat_core.so](https://file+.vscode-resource.vscode-cdn.net/home/slp/anaconda3/envs/icefall_test/lib/python3.11/site-packages/kaldifeat/lib64/libkaldifeat_core.so))
frame #13: kaldifeat::FbankComputer::FbankComputer(kaldifeat::FbankOptions const&) + 0xc9 (0x7f211b02e709 in [/home/slp/anaconda3/envs/icefall_test/lib/python3.11/site-packages/kaldifeat/lib64/libkaldifeat_core.so](https://file+.vscode-resource.vscode-cdn.net/home/slp/anaconda3/envs/icefall_test/lib/python3.11/site-packages/kaldifeat/lib64/libkaldifeat_core.so))
frame #14: <unknown function> + 0x444fa (0x7f211b0d24fa in [/home/slp/anaconda3/envs/icefall_test/lib/python3.11/site-packages/_kaldifeat.cpython-311-x86_64-linux-gnu.so](https://file+.vscode-resource.vscode-cdn.net/home/slp/anaconda3/envs/icefall_test/lib/python3.11/site-packages/_kaldifeat.cpython-311-x86_64-linux-gnu.so))
frame #15: <unknown function> + 0x4e00a (0x7f211b0dc00a in [/home/slp/anaconda3/envs/icefall_test/lib/python3.11/site-packages/_kaldifeat.cpython-311-x86_64-linux-gnu.so](https://file+.vscode-resource.vscode-cdn.net/home/slp/anaconda3/envs/icefall_test/lib/python3.11/site-packages/_kaldifeat.cpython-311-x86_64-linux-gnu.so))
frame #16: python3() [0x525f07]
<omitting python frames>
frame #18: python3() [0x554172]
frame #19: python3() [0x53cd22]
frame #20: python3() [0x50327c]
frame #21: <unknown function> + 0x3b014 (0x7f2121e3b014 in [/home/slp/anaconda3/envs/icefall_test/lib/python3.11/site-packages/_k2.cpython-311-x86_64-linux-gnu.so](https://file+.vscode-resource.vscode-cdn.net/home/slp/anaconda3/envs/icefall_test/lib/python3.11/site-packages/_k2.cpython-311-x86_64-linux-gnu.so))
frame #25: python3() [0x53c9bf]
frame #29: python3() [0x53c9bf]
frame #32: python3() [0x5c82ce]
frame #34: python3() [0x5e8807]
frame #35: python3() [0x5e4e40]
frame #36: python3() [0x5f9132]
frame #41: <unknown function> + 0x29d90 (0x7f21c6e29d90 in [/lib/x86_64-linux-gnu/libc.so.6](https://file+.vscode-resource.vscode-cdn.net/lib/x86_64-linux-gnu/libc.so.6))
frame #42: __libc_start_main + 0x80 (0x7f21c6e29e40 in [/lib/x86_64-linux-gnu/libc.so.6](https://file+.vscode-resource.vscode-cdn.net/lib/x86_64-linux-gnu/libc.so.6))
frame #43: python3() [0x5b6c6f]
```
tất nhiên là nếu không sửa thì code sẽ chạy với cpu :100: 
![Screenshot from 2024-01-12 16-03-35](https://github.com/k2-fsa/icefall/assets/144792281/e51244df-0c4f-4c57-8655-d733ca49d103)

**Comment by csukuangfj** [comment]
What's the output of
nvidia-smi?

**Comment by quanganhdao2k2** [comment]
![Screenshot from 2024-01-15 09-22-25](https://github.com/k2-fsa/icefall/assets/144792281/30192571-f5f3-4458-a414-57e85e99735b)
its like this @csukuangfj

**Comment by csukuangfj** [comment]
> Hello everyone,
> 
> I am currently reproducing the results of PromptASR. However, I am encountering an issue when running prepare.sh stage 7. I have checked the GPU and the environment, but it still doesn't work. It continues to use the CPU and takes a considerable amount of time to process. I have checked the code [here](https://github.com/k2-fsa/icefall/blob/e2fcb42f5f176d9e39eb38506ab99d0a3adaf202/egs/libriheavy/ASR/local/compute_fbank_libriheavy.py#L186)
> 
> ![Screenshot from 2024-01-12 12-00-02](https://private-user-images.githubusercontent.com/144792281/296133195-3259427a-9493-4265-9bf5-f0a931891dfa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyODYyNDYsIm5iZiI6MTcwNTI4NTk0NiwicGF0aCI6Ii8xNDQ3OTIyODEvMjk2MTMzMTk1LTMyNTk0MjdhLTk0OTMtNDI2NS05YmY1LWYwYTkzMTg5MWRmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNVQwMjMyMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMWI3MDgzMDcyODE5ZDlhYWNiMjc4OGJiYzc4OWU3OWM3NTFjYjZkODFiMjVjZTQ2MDY3MzBjMmEyYzRmNGQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.u1UAvD4VG1cg7b3KLGA1W18oMd0W_XQrwDQz3h1-y4Y) ![Screenshot from 2024-01-12 11-58-58](https://private-user-images.githubusercontent.com/144792281/296133200-56697033-3c98-48d6-ad86-83aaa4b593c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyODYyNDYsIm5iZiI6MTcwNTI4NTk0NiwicGF0aCI6Ii8xNDQ3OTIyODEvMjk2MTMzMjAwLTU2Njk3MDMzLTNjOTgtNDhkNi1hZDg2LTgzYWFhNGI1OTNjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNVQwMjMyMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NjMxNWQ3NjA1MDhkNGUyOTc4OGFlMWZhZGU5Yjg2NzVkMzQ0MmM3MjBmY2Q3N2NhMTdmMWVhZDA5MjY1ZTE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qRwWl5tdvzs50iy8HRSe4IQXKZrxFmdqk80D-zg37N4) Here is the error image I encountered. Has anyone experienced a similar issue? Thank you for any contributions from you.

From the output of `nvcc --version`, it shows your nvcc is for cuda 9.1, but your torch, kaldifeat, and k2 are for `cuda 12.1`.

Could you follow
https://k2-fsa.github.io/k2/installation/cuda-cudnn.html
to install cuda 12.1?

Remember to restart your notebook after installation.

**Comment by quanganhdao2k2** [comment]
```python
!which nvcc
!nvcc --version
```
then show output like this:
```python
/home/slp/anaconda3/envs/k2_conda/bin/nvcc
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Feb__7_19:32:13_PST_2023
Cuda compilation tools, release 12.1, V12.1.66
Build cuda_12.1.r12.1/compiler.32415258_0
```
and I still get the same error
```python
2024-01-15 12:30:09 (prepare.sh:56:main) dl_dir: [/media/slp/slp_4T/Thachhs/k2_icefall/icefall/egs/libriheavy/ASR/download](https://file+.vscode-resource.vscode-cdn.net/media/slp/slp_4T/Thachhs/k2_icefall/icefall/egs/libriheavy/ASR/download)
2024-01-15 12:30:09 (prepare.sh:180:main) Stage 7: Compute fbank for medium and large subsets
2024-01-15 12:30:11,108 INFO [compute_fbank_libriheavy.py:237] {'manifest_dir': 'data/manifests', 'fbank_dir': 'data/fbank', 'subset': 'medium', 'num_workers': 15, 'batch_duration': 600.0, 'perturb_speed': False, 'use_splits': True, 'num_splits': 138, 'start': 60, 'stop': 80}
2024-01-15 12:30:11,110 INFO [compute_fbank_libriheavy.py:237] {'manifest_dir': 'data/manifests', 'fbank_dir': 'data/fbank', 'subset': 'medium', 'num_workers': 15, 'batch_duration': 600.0, 'perturb_speed': False, 'use_splits': True, 'num_splits': 138, 'start': 120, 'stop': 140}
2024-01-15 12:30:11,110 INFO [compute_fbank_libriheavy.py:237] {'manifest_dir': 'data/manifests', 'fbank_dir': 'data/fbank', 'subset': 'medium', 'num_workers': 15, 'batch_duration': 600.0, 'perturb_speed': False, 'use_splits': True, 'num_splits': 138, 'start': 0, 'stop': 20}
2024-01-15 12:30:11,110 INFO [compute_fbank_libriheavy.py:237] {'manifest_dir': 'data/manifests', 'fbank_dir': 'data/fbank', 'subset': 'medium', 'num_workers': 15, 'batch_duration': 600.0, 'perturb_speed': False, 'use_splits': True, 'num_splits': 138, 'start': 20, 'stop': 40}
2024-01-15 12:30:11,110 INFO [compute_fbank_libriheavy.py:237] {'manifest_dir': 'data/manifests', 'fbank_dir': 'data/fbank', 'subset': 'medium', 'num_workers': 15, 'batch_duration': 600.0, 'perturb_speed': False, 'use_splits': True, 'num_splits': 138, 'start': 80, 'stop': 100}
2024-01-15 12:30:11,112 INFO [compute_fbank_libriheavy.py:237] {'manifest_dir': 'data/manifests', 'fbank_dir': 'data/fbank', 'subset': 'medium', 'num_workers': 15, 'batch_duration': 600.0, 'perturb_speed': False, 'use_splits': True, 'num_splits': 138, 'start': 40, 'stop': 60}
2024-01-15 12:30:11,114 INFO [compute_fbank_libriheavy.py:237] {'manifest_dir': 'data/manifests', 'fbank_dir': 'data/fbank', 'subset': 'medium', 'num_workers': 15, 'batch_duration': 600.0, 'perturb_speed': False, 'use_splits': True, 'num_splits': 138, 'start': 100, 'stop': 120}
Traceback (most recent call last):
  File "/media/slp/slp_4T/Thachhs/k2_icefall/icefall/egs/libriheavy/ASR/./local/compute_fbank_libriheavy.py", line 241, in <module>
Traceback (most recent call last):
  File "/media/slp/slp_4T/Thachhs/k2_icefall/icefall/egs/libriheavy/ASR/./local/compute_fbank_libriheavy.py", line 241, in <module>
    compute_fbank_libriheavy_splits(args)
  File "/media/slp/slp_4T/Thachhs/k2_icefall/icefall/egs/libriheavy/ASR/./local/compute_fbank_libriheavy.py", line 188, in compute_fbank_libriheavy_splits
    compute_fbank_libriheavy_splits(args)
  File "/media/slp/slp_4T/Thachhs/k2_icefall/icefall/egs/libriheavy/ASR/./local/compute_fbank_libriheavy.py", line 188, in compute_fbank_libriheavy_splits
    extractor = KaldifeatFbank(KaldifeatFbankConfig(device=device))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/slp/anaconda3/envs/k2_conda/lib/python3.11/site-packages/lhotse/features/kaldifeat.py", line 189, in __init__
    extractor = KaldifeatFbank(KaldifeatFbankConfig(device=device))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^    self.extractor = kaldifeat.Fbank(

               Traceback (most recent call last):
     File "/media/slp/slp_4T/Thachhs/k2_icefall/icefall/egs/libriheavy/ASR/./local/compute_fbank_libriheavy.py", line 241, in <module>
   ^^^^^Traceback (most recent call last):
^^^  File "/home/slp/anaconda3/envs/k2_conda/lib/python3.11/site-packages/lhotse/features/kaldifeat.py", line 189, in __init__
^^^^^^^^
  File "/home/slp/anaconda3/envs/k2_conda/lib/python3.11/site-packages/kaldifeat/fbank.py", line 13, in __init__
    compute_fbank_libriheavy_splits(args)
  File "/media/slp/slp_4T/Thachhs/k2_icefall/icefall/egs/libriheavy/ASR/./local/compute_fbank_libriheavy.py", line 188, in compute_fbank_libriheavy_splits
    self.extractor = kaldifeat.Fbank(
          extractor = KaldifeatFbank(KaldifeatFbankConfig(device=device))
                ^^^^^^^^^^^^^^^^^^    self.computer = _kaldifeat.Fbank(opts)
         File "/media/slp/slp_4T/Thachhs/k2_icefall/icefall/egs/libriheavy/ASR/./local/compute_fbank_libriheavy.py", line 241, in <module>
            ^     ^ ^^         ^^^ ^^^^^^^    ^compute_fbank_libriheavy_splits(args)^
^^^^^^^  File "/media/slp/slp_4T/Thachhs/k2_icefall/icefall/egs/libriheavy/ASR/./local/compute_fbank_libriheavy.py", line 188, in compute_fbank_libriheavy_splits
    extractor = KaldifeatFbank(KaldifeatFbankConfig(device=device))
      
   ^ ^^  File "/home/slp/anaconda3/envs/k2_conda/lib/python3.11/site-packages/kaldifeat/fbank.py", line 13, in __init__
      ^^^^^^^^^^^^^^^^^^^^^
^^RuntimeError: ^CUDA error: no CUDA-capable device is detected
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Device-side assertions were explicitly omitted for this error check; the error probably arose while initializing the DSA handlers.
Exception raised from c10_cuda_check_implementation at [/opt/conda/conda-bld/pytorch_1702400430266/work/c10/cuda/CUDAException.cpp:44](https://file+.vscode-resource.vscode-cdn.net/opt/conda/conda-bld/pytorch_1702400430266/work/c10/cuda/CUDAException.cpp:44) (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f4d80f15617 in [/home/slp/anaconda3/envs/k2_conda/lib/python3.11/site-packages/torch/lib/libc10.so](https://file+.vscode-resource.vscode-cdn.net/home/slp/anaconda3/envs/k2_conda/lib/python3.11/site-packages/torch/lib/libc10.so))
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7f4d80ed098d in [/home/slp/anaconda3/envs/k2_conda/lib/python3.11/site-packages/torch/lib/libc10.so](https://file+.vscode-resource.vscode-cdn.net/home/slp/anaconda3/envs/k2_conda/lib/python3.11/site-packages/torch/lib/libc10.so))
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x118 (0x7f4d80fd2128 in [/home/slp/anaconda3/envs/k2_conda/lib/python3.11/site-packages/torch/lib/libc10_cuda.so](https://file+.vscode-resource.vscode-cdn.net/home/slp/anaconda3/envs/k2_conda/lib/python3.11/site-packages/torch/lib/libc10_cuda.so))
frame #3: c10::cuda::CUDAKernelLaunchRegistry::CUDAKernelLaunchRegistry() + 0x9d (0x7f4d80fd17fd in [/home/slp/anaconda3/envs/k2_conda/lib/python3.11/site-packages/torch/lib/libc10_cuda.so](https://file+.vscode-resource.vscode-cdn.net/home/slp/anaconda3/envs/k2_conda/lib/python3.11/site-packages/torch/lib/libc10_cuda.so))
frame #4: c10::cuda::CUDAKernelLaunchRegistry::get_singleton_ref() + 0x44 (0x7f4d80fd19c4 in [/home/slp/anaconda3/envs/k2_conda/lib/python3.11/site-packages/torch/lib/libc10_cuda.so](https://file+.vscode-resource.vscode-cdn.net/home/slp/anaconda3/envs/k2_conda/lib/python3.11/site-packages/torch/lib/libc10_cuda.so))
frame #5: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x35 (0x7f4d80fd2045 in [/home/slp/anaconda3/envs/k2_conda/lib/python3.11/site-packages/torch/lib/libc10_cuda.so](https://file+.vscode-resource.vscode-cdn.net/home/slp/anaconda3/envs/k2_conda/lib/python3.11/site-packages/torch/lib/libc10_cuda.so))
frame #6: <unknown function> + 0x1c0de (0x7f4d80fa00de in [/home/slp/anaconda3/envs/k2_conda/lib/python3.11/site-packages/torch/lib/libc10_cuda.so](https://file+.vscode-resource.vscode-cdn.net/home/slp/anaconda3/envs/k2_conda/lib/python3.11/site-packages/torch/lib/libc10_cuda.so))
frame #7: at::native::to(at::Tensor const&, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>, bool, bool, c10::optional<c10::MemoryFormat>) + 0x179 (0x7f4d2f6180f9 in [/home/slp/anaconda3/envs/k2_conda/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so](https://file+.vscode-resource.vscode-cdn.net/home/slp/anaconda3/envs/k2_conda/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so))
frame #8: <unknown function> + 0x2995681 (0x7f4d30595681 in [/home/slp/anaconda3/envs/k2_conda/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so](https://file+.vscode-resource.vscode-cdn.net/home/slp/anaconda3/envs/k2_conda/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so))
frame #9: at::_ops::to_dtype_layout::call(at::Tensor const&, c10::optional<c10::ScalarType>, c10::optional<c10::Layout>, c10::optional<c10::Device>, c10::optional<bool>, bool, bool, c10::optional<c10::MemoryFormat>) + 0x203 (0x7f4d2fd42dc3 in [/home/slp/anaconda3/envs/k2_conda/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so](https://file+.vscode-resource.vscode-cdn.net/home/slp/anaconda3/envs/k2_conda/lib/python3.11/site-packages/torch/lib/libtorch_cpu.so))
frame #10: <unknown function> + 0x20e27 (0x7f4cdabb3e27 in [/home/slp/anaconda3/envs/k2_conda/lib/python3.11/site-packages/kaldifeat/lib64/libkaldifeat_core.so](https://file+.vscode-resource.vscode-cdn.net/home/slp/anaconda3/envs/k2_conda/lib/python3.11/site-packages/kaldifeat/lib64/libkaldifeat_core.so))
frame #11: kaldifeat::MelBanks::MelBanks(kaldifeat::MelBanksOptions const&, kaldifeat::FrameExtractionOptions const&, float, c10::Device) + 0xb01 (0x7f4cdabb5121 in [/home/slp/anaconda3/envs/k2_conda/lib/python3.11/site-packages/kaldifeat/lib64/libkaldifeat_core.so](https://file+.vscode-resource.vscode-cdn.net/home/slp/anaconda3/envs/k2_conda/lib/python3.11/site-packages/kaldifeat/lib64/libkaldifeat_core.so))
frame #12: kaldifeat::FbankComputer::GetMelBanks(float) + 0x90 (0x7f4cdaba0540 in [/home/slp/anaconda3/envs/k2_conda/lib/python3.11/site-packages/kaldifeat/lib64/libkaldifeat_core.so](https://file+.vscode-resource.vscode-cdn.net/home/slp/anaconda3/envs/k2_conda/lib/python3.11/site-packages/kaldifeat/lib64/libkaldifeat_core.so))
frame #13: kaldifeat::FbankComputer::FbankComputer(kaldifeat::FbankOptions const&) + 0xc9 (0x7f4cdaba0709 in [/home/slp/anaconda3/envs/k2_conda/lib/python3.11/site-packages/kaldifeat/lib64/libkaldifeat_core.so](https://file+.vscode-resource.vscode-cdn.net/home/slp/anaconda3/envs/k2_conda/lib/python3.11/site-packages/kaldifeat/lib64/libkaldifeat_core.so))
frame #14: <unknown function> + 0x444fa (0x7f4cf21a64fa in [/home/slp/anaconda3/envs/k2_conda/lib/python3.11/site-packages/_kaldifeat.cpython-311-x86_64-linux-gnu.so](https://file+.vscode-resource.vscode-cdn.net/home/slp/anaconda3/envs/k2_conda/lib/python3.11/site-packages/_kaldifeat.cpython-311-x86_64-linux-gnu.so))
frame #15: <unknown function> + 0x4e00a (0x7f4cf21b000a in [/home/slp/anaconda3/envs/k2_conda/lib/python3.11/site-packages/_kaldifeat.cpython-311-x86_64-linux-gnu.so](https://file+.vscode-resource.vscode-cdn.net/home/slp/anaconda3/envs/k2_conda/lib/python3.11/site-packages/_kaldifeat.cpython-311-x86_64-linux-gnu.so))
frame #16: python3() [0x525f07]
<omitting python frames>
```
Should I uninstall and reinstall the environment from scratch? @csukuangfj , ah, i ran it using anaconda : <

**Comment by csukuangfj** [comment]
Have you tried to run it in a script within a terminal, not a notebook?

**Comment by quanganhdao2k2** [comment]
I will try running with terminal, or reinstall the environment from scratch, maybe I made a mistake somewhere

**Comment by quanganhdao2k2** [comment]
@csukuangfj hi, I took the time to install the environment following the instructions from scratch and it works with my GPU. I use ***torch 2.2.0 cuda 121***. I tried with run script and notebook and it works fine. Thank you.
