### ISSUE TITLE
librispeech/ASR/zipformer/train.py fails on CTC loss calc with cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by al-zatv-mybuddy-ai** [k2-fsa/icefall#1963]
I am trying to make streaming zipformer with CTC, using command-line params from 
`https://huggingface.co/csukuangfj/icefall-asr-librispeech-streaming-zipformer-small-2024-03-18/blob/main/run-streaming-zipformer-ctc.sh`

This code fails with `RuntimeError: CUDA error: an illegal memory access was encountered`. 

After runing `CUDA_LAUNCH_BLOCKING=1 ./run_train.sh`, it fails with error `RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED` on CTC loss calculation code here, during OOM sanity check (or later, during training, if I turn off the check):

https://github.com/k2-fsa/icefall/blob/ffb7d0563526f42123d2c65c284646a5c375b74f/egs/librispeech/ASR/zipformer/model.py#L176

I see this problem on original librispeech dataset, and on my custom dataset.

icefall repo was updated yesterday, k2's version is 1.24.4.dev20250304+cuda11.8.torch2.6.0, torch.__version__ is 2.6.0+cu118, cuda 12.9, GPU 4xNvidiaT4 @ Google GCP

**Comment by al-zatv-mybuddy-ai** [comment]
This problem looks very similar to this: 

https://github.com/pytorch/pytorch/issues/152421?ysclid=mbquz0j33t903094735

Fix for it was merged to pytorch in 8th of may, while fresh release of pytorch (2.7.1) was made in 1st of may. So this problem is not fixed in release version of pytorch. Following the description of the problem, I change
https://github.com/k2-fsa/icefall/blob/ffb7d0563526f42123d2c65c284646a5c375b74f/egs/librispeech/ASR/zipformer/model.py#L176

to: 
```
        ctc_loss = torch.nn.functional.ctc_loss(                                                                                                                                                              
            log_probs=ctc_output.permute(1, 0, 2),  # (T, N, C)                                                                                                                                               
            targets=targets.cpu(),                                                                                                                                                                            
            input_lengths=encoder_out_lens.cuda(),#AP:was: .cpu(),                                                                                                                                                  
            target_lengths=target_lengths.cuda(),#AP:was: .cpu(),                                                                                                                                                   
            reduction="sum",                                                                                                                                                                                  
        )
```
And now it's training. 

But after some iterations, it shows multiple warnings, gradient scaler goes down to it's limit and terminates training. Don't know if it's a separate issue (because if I turn off transducer and attention-decoder parts (`--use-transducer 0 --use-attention-decoder 0`), I don't see any warnings, and everything looks good,at first glance)

**Comment by al-zatv-mybuddy-ai** [comment]
> But after some iterations, it shows multiple warnings, gradient scaler goes down to it's limit and terminates training. Don't know if it's a separate issue (because if I turn off transducer and attention-decoder parts (`--use-transducer 0 --use-attention-decoder 0`), I don't see any warnings, and everything looks good,at first glance)

Warnings mentioned above are:
```
bsr2venv/lib/python3.11/site-packages/torch/nn/modules/module.py:1830: FutureWarning: Using a non-full backward hook when outputs are generated by different autograd Nod
es is deprecated and will be removed in future versions. This hook will be missing some grad_output. Please use register_full_backward_hook to get the documented behavior.                                   
  self._maybe_warn_non_full_backward_hook(args, result, grad_fn)                                                                                                                                              
2025-06-11 11:20:37,283 WARNING [train.py:1177] (1/4) Grad scale is small: 0.0078125                                                                                                                          
2025-06-11 11:20:37,286 WARNING [train.py:1177] (2/4) Grad scale is small: 0.0078125                                                                                                                          
2025-06-11 11:20:37,290 WARNING [train.py:1177] (0/4) Grad scale is small: 0.0078125                                                                                                                          2025-06-11 11:20:37,291 WARNING [train.py:1177] (3/4) Grad scale is small: 0.0078125                                                                                                                          
bsr2venv/lib/python3.11/site-packages/torch/nn/modules/module.py:1830: FutureWarning: Using a non-full backward hook when the forward contains multiple autograd Nodes is
 deprecated and will be removed in future versions. This hook will be missing some grad_input. Please use register_full_backward_hook to get the documented behavior.                                         
  self._maybe_warn_non_full_backward_hook(args, result, grad_fn)                                                                                                                                              
```
etc etc etc

**Comment by csukuangfj** [comment]
I think that is a bug with cudnn ctc

If you change the dtype of the target or input length from
torch.int32
to
torch.int64

,

you.can avoid this error.

**Comment by al-zatv-mybuddy-ai** [comment]
> If you change the dtype of the target or input length from
> torch.int32
> to
> torch.int64

Thank you for answer! Will try. Did you mean to do smth like
```
ctc_loss = torch.nn.functional.ctc_loss(                                                                                                                                                              
            log_probs=ctc_output.permute(1, 0, 2),  # (T, N, C)                                                                                                                                               
            targets=targets.cpu(),                                                                                                                                                                            
            input_lengths=encoder_out_lens.cpu().to(torch.int64),#AP:was: encoder_out_lens.cpu(),                                                                                                                                                  
            target_lengths=target_lengths.cpu(),                                                                                                                                                   
            reduction="sum",                                                                                                                                                                                  
        ) 
```
or to go there this encoder_out_lens are generated (in encoder.forward,pbbly), and change there?

**Comment by csukuangfj** [comment]
Yes, your are right.

**Comment by csukuangfj** [comment]
> > If you change the dtype of the target or input length from torch.int32 to torch.int64
> 
> Problem solved,as I mentioned above. Should I close this issue, or may be you want to keep it open till fix in zipformer/train.py appear?

I think we can leave it open.

This error depends on the version of PyTorch you use. Disable cudnn may affect performance in speed.
